# Generated by Django 4.1.3 on 2022-11-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageschat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='count_readers',
            field=models.IntegerField(default=0, verbose_name='Количество прочтений'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
