# Generated by Django 4.1.3 on 2022-11-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageschat', '0002_message_count_readers_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Изменено'),
        ),
    ]
