# Generated by Django 4.1.3 on 2022-11-01 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0003_chat_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_chats', to=settings.AUTH_USER_MODEL), related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
