# Generated by Django 4.1.3 on 2022-11-14 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0005_alter_chat_options_remove_chat_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='creator',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chats', to=settings.AUTH_USER_MODEL, verbose_name='Администратор чата'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='added_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by_user_members', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователья'),
        ),
    ]
