# Generated by Django 4.1.3 on 2022-11-15 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0006_remove_chat_creator_chat_chat_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='added_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by_user_members', to=settings.AUTH_USER_MODEL, verbose_name='ID добавившего пользователя'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_members', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
    ]
