# Generated by Django 4.1.3 on 2022-11-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_chatmember_added_by_user_alter_chatmember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_admin',
        ),
        migrations.AddField(
            model_name='chatmember',
            name='chat_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='muted',
            field=models.BooleanField(default=False, verbose_name='Включены уведомления'),
        ),
    ]
