# Generated by Django 4.1.3 on 2022-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_remove_chat_chat_admin_chatmember_chat_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Приватный'),
        ),
    ]
