# Generated by Django 4.1.3 on 2022-11-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_alter_chatmember_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmember',
            name='muted',
            field=models.BooleanField(default=False, verbose_name='Выключены уведомления'),
        ),
    ]
