# Generated by Django 4.1.2 on 2022-10-25 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
