# Generated by Django 4.1.3 on 2022-11-01 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_contacts_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
