# Generated by Django 4.1.3 on 2022-11-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=79999999999, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
