# Generated by Django 4.1.3 on 2022-11-19 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_contacts_alter_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(related_name='user_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Контакты'),
        ),
    ]
