# Generated by Django 4.1.3 on 2022-11-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contacts',
        ),
    ]
