# Generated by Django 4.1.3 on 2022-11-19 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.ManyToManyField(related_name='kek', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactbook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
