# Generated by Django 4.1.3 on 2022-11-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_contactbook_options_alter_contactbook_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
